// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz-mX4Zp-Kpm6DusOyrOLtAmHcQ8Jl8ko',
    appId: '1:766566480084:web:e1be44cd159a2e204fa341',
    messagingSenderId: '766566480084',
    projectId: 'aircon-cc3d0',
    authDomain: 'aircon-cc3d0.firebaseapp.com',
    databaseURL: 'https://aircon-cc3d0-default-rtdb.firebaseio.com',
    storageBucket: 'aircon-cc3d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM2I4F234zZuGbdLqhM2YOtoLh9MmEqDo',
    appId: '1:766566480084:android:566923388890b82e4fa341',
    messagingSenderId: '766566480084',
    projectId: 'aircon-cc3d0',
    databaseURL: 'https://aircon-cc3d0-default-rtdb.firebaseio.com',
    storageBucket: 'aircon-cc3d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD697aMyR6PYw9h6U5uqwM4Zy08LwCajc0',
    appId: '1:766566480084:ios:557cb6e227b223fb4fa341',
    messagingSenderId: '766566480084',
    projectId: 'aircon-cc3d0',
    databaseURL: 'https://aircon-cc3d0-default-rtdb.firebaseio.com',
    storageBucket: 'aircon-cc3d0.firebasestorage.app',
    iosBundleId: 'com.example.aircon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD697aMyR6PYw9h6U5uqwM4Zy08LwCajc0',
    appId: '1:766566480084:ios:557cb6e227b223fb4fa341',
    messagingSenderId: '766566480084',
    projectId: 'aircon-cc3d0',
    databaseURL: 'https://aircon-cc3d0-default-rtdb.firebaseio.com',
    storageBucket: 'aircon-cc3d0.firebasestorage.app',
    iosBundleId: 'com.example.aircon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz-mX4Zp-Kpm6DusOyrOLtAmHcQ8Jl8ko',
    appId: '1:766566480084:web:8dc89dc7d10bbfa64fa341',
    messagingSenderId: '766566480084',
    projectId: 'aircon-cc3d0',
    authDomain: 'aircon-cc3d0.firebaseapp.com',
    databaseURL: 'https://aircon-cc3d0-default-rtdb.firebaseio.com',
    storageBucket: 'aircon-cc3d0.firebasestorage.app',
  );
}
